# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=120)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'attendee',
                'verbose_name_plural': 'attendees',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='You may use HTML tags')),
                ('email_description', models.TextField(help_text='You may use HTML tags')),
                ('member_fee', models.PositiveIntegerField(help_text='Enter amount in cents.', verbose_name='member fee')),
                ('non_member_fee', models.PositiveIntegerField(help_text='Enter amount in cents.', verbose_name='non-member fee')),
                ('start_date', models.DateTimeField(verbose_name='start date of event')),
                ('end_date', models.DateTimeField(verbose_name='end date of event')),
                ('is_active', models.BooleanField(default=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='event_attendees', to='events.Attendee')),
                ('sponsors', models.ManyToManyField(blank=True, related_name='event_sponsors', to='accounts.Sponsor')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
