# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField(verbose_name='Start of Event')),
                ('end_date', models.DateTimeField(verbose_name='End of Event')),
                ('image', models.ImageField(blank=True, help_text='Please upload an image with\n                               sizes: (W - 750px | H - 300px).', upload_to=events.models.image_upload_loc, verbose_name='event image')),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('sponsors', models.ManyToManyField(blank=True, help_text='Select the magnifying glass\n                                       to add sponsors.', related_name='event_sponsors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
