# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField(verbose_name='Date of Event')),
                ('is_active', models.BooleanField(default=True)),
                ('sponsors', models.ManyToManyField(blank=True, related_name='event_sponsors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
