# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, help_text='Select the magnifying glass\n                                       to add sponsors.', related_name='event_sponsors', to='accounts.Sponsor'),
        ),
    ]
