# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 13:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in dollars.', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='member fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='non_member_fee',
            field=models.DecimalField(decimal_places=2, help_text='Amount in dollars.', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='non-member fee'),
        ),
    ]
