# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Please upload an image with\n                               sizes: (W - 750px | H - 300px)', upload_to=events.models.image_upload_loc, verbose_name='event image'),
        ),
    ]
