# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170203_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member_fee',
            field=models.PositiveIntegerField(help_text='Value in cents.', verbose_name='member fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='non_member_fee',
            field=models.PositiveIntegerField(help_text='Value in cents.', verbose_name='non-member fee'),
        ),
    ]
