# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170104_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='non_member_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
            preserve_default=False,
        ),
    ]
