# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160910_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Please upload an image with\n                               sizes: (W - 750px | H - 300px).', upload_to=events.models.image_upload_loc, verbose_name='event image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, help_text='Select the magnifying glass\n                                       to add sponsors.', related_name='event_sponsors', to=settings.AUTH_USER_MODEL),
        ),
    ]
