# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170105_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='You may use HTML when rendering', max_length=2000),
        ),
    ]
