# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 12:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170105_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='non_member_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
