# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170329_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_description',
            field=models.TextField(default='', help_text='You may use HTML tags'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='You may use HTML tags'),
        ),
    ]
