# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 13:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170105_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(verbose_name='end date of event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='member_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='member fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='non_member_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='non-member fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date of event'),
        ),
    ]
