# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 14:15
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='next_billing_fee',
        ),
        migrations.AddField(
            model_name='membership',
            name='billing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='next billing fee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 14, 15, 36, 172744)),
        ),
    ]
