# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.PositiveIntegerField(help_text='A positive integer in cents (or 0 for a free plan) representing how much to charge (on a recurring basis).'),
        ),
    ]
