# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='customer',
        ),
    ]
