# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.PositiveIntegerField(help_text='A positive integer in cents (or 0 for a free plan) representing how much to charge (on a recurring basis).', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.PositiveIntegerField(help_text='A positive integer in cents (or 0 for a free plan) representing how much to charge (on a recurring basis).'),
        ),
    ]
