# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20170113_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business_vat_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_source',
        ),
    ]
