# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20170113_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tax_percent',
        ),
    ]
