# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20170113_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='application_fee_percent',
        ),
    ]
