# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_subscription_application_fee_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
