# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20170117_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trial_end',
        ),
    ]
