# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_subscription_trial_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_date',
        ),
    ]
