# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20170118_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='fraud_details',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='metadata',
        ),
    ]
