# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
