# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170404_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Newsletter',
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
    ]
