# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='billing_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 13, 6, 59, 816466), verbose_name='billing end date'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='billing_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='billing start date'),
            preserve_default=False,
        ),
    ]
