# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='company name'),
        ),
    ]
