# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 15:12
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='logo',
            field=models.ImageField(blank=True, upload_to=accounts.models.logo_upload_loc, verbose_name='company logo'),
        ),
    ]
