# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Allows users to create events.', verbose_name='staff'),
        ),
    ]
