# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161220_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
