# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170105_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='billing_end',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='billing_start',
        ),
    ]
