# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 22:23
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160910_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='logo',
            field=models.ImageField(blank=True, help_text='Please upload an image with\n                              sizes: (W - 488px | H - 150px)', upload_to=accounts.models.logo_upload_loc, verbose_name='company logo'),
        ),
    ]
